[metadata.heroku]
  root-package = "github.com/mikedonnici/rtcl-api"
  go-version = "1.10"
  install = [ "./..." ]

[[constraint]]
  branch = "master"
  name = "github.com/34South/envr"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-uuid"

[[constraint]]
  name = "github.com/matryer/is"
  version = "1.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.5.0"

[[constraint]]
  name = "github.com/sendgrid/sendgrid-go"
  version = "3.4.1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
